### ISSUE TITLE
Adjusting Data

### ISSUE THREAD

**Issue by AniSanikidze** [adzai/chatbot#10]
Modifying values to sentences.

**Comment by irinakulinich3712** [comment]
Most likely, we will need to separate the park data and chatbot's response sentences, according to Petr's suggestion. This will allow more flexibility and to have general response patterns based on the values, instead of specifying them for each park

**Comment by adzai** [comment]
Some values are specific for each park in the current dataset. However I don't really care, if you want to redo it this way you can make another PR.

**Comment by AniSanikidze** [comment]
Because we have different, detailed information (sentences) for every park and not just yes or no. I think it is better to stick with Adam's idea to have a keyword and an appropriate value which will be used in the conversation as a reply. Or we can remove details from the data and do what Iryna said. But the chatbot will be less informative.

**Comment by adzai** [comment]
To clarify, I see it like this:
---

1. User inputs a sentence
2. We extract the words into a vector
3. Pair each of these words with the likelihood of it corresponding to a tag (json key value).
4. Pick the highest one if it meets a certain threshold
5. Access the value of this json key, which should be the sentence / array of sentences
6. Respond to the user with this sentence

---
As I said, if you have something better in mind, we can try that.

**Comment by AniSanikidze** [comment]
As I said, I like Adam's solution. We just need to decide whether we prefer flexibility over informativeness or vice versa.

**Comment by AniSanikidze** [comment]
Guys, Petr said that it's better to have mere but flexible reply sentences.  I suggest creating a separate json file containing information about a specific park, for example, Bertramka and use it for ica1.  Also, Petr approved that in the greeting part, the bot should make it clear that it will provide info only about the bertramka park and will say something like this: Hello, let me know what questions you have regarding bertramka. 

For now, I will create separate json file for Bertramka and will update the data in general.

**Comment by adzai** [comment]
I think it might be a headache in ICA2 to switch between files for different parks, but we'll see.
