### ISSUE TITLE
Translate data about parks

### ISSUE THREAD

**Issue by irinakulinich3712** [adzai/chatbot#2]
Translating collected data about Prague parks from Czech to English

**Comment by adzai** [comment]
Please close this after it's merged to main.

**Comment by irinakulinich3712** [comment]
> Please close this after it's merged to main.

Why? The task is finished, we don't need the issue anymore

**Comment by adzai** [comment]
If a task is completely finished, it has to be merged to main (master) branch. Otherwise we might forget about it and work on the master branch that is not complete - might cause conflicts in the future.

**Comment by irinakulinich3712** [comment]
> If a task is completely finished, it has to be merged to main (master) branch. Otherwise we might forget about it and work on the master branch that is not complete - might cause conflicts in the future.

Then, we are merging the Data branch into Main as it is redundant
