### ISSUE TITLE
Keywords which are more than 1 word

### ISSUE THREAD

**Issue by adzai** [adzai/chatbot#21]
Currently we have some keywords which consist of multiple words. This will make parsing the sentence and doing a word-wise comparison between inputted word/words and our keyword tag nearly impossible (not to mention keywords in clojure must be 1 word). For that reason I would suggest to limit ourselves to only 1 word keywords and synonyms.

**Comment by AniSanikidze** [comment]
Agree with you, we can easily change them. For example, bike paths can be written as biking.

**Comment by AniSanikidze** [comment]
I'll try to change them.

**Comment by AniSanikidze** [comment]
Also, for matching, I think that all the keywords in the JSON file must be lowercased as the "parse-user-input" function lower-cases all words existing in the user input.

**Comment by irinakulinich3712** [comment]
> Currently we have some keywords which consist of multiple words. This will make parsing the sentence and doing a word-wise comparison between inputted word/words and our keyword tag nearly impossible (not to mention keywords in clojure must be 1 word). For that reason I would suggest to limit ourselves to only 1 word keywords and synonyms.

You are right, I will edit the synonyms as well

**Comment by irinakulinich3712** [comment]
> I'll try to change them.

Actually, which single-word keyword do you suggest to use for "sports field"? As I need to modify the synonyms now

**Comment by AniSanikidze** [comment]
> > I'll try to change them.
> 
> Actually, which single-word keyword do you suggest to use for "sports field"? As I need to modify the synonyms now

"wc","attractions","biking","skating","sports","playground","transportation","parking","roads","operator" and "open". These are the current, updated keywords. If this is okay for you, I will push it to the branch.

**Comment by irinakulinich3712** [comment]
> > > I'll try to change them.
> > 
> > 
> > Actually, which single-word keyword do you suggest to use for "sports field"? As I need to modify the synonyms now
> 
> "wc","attractions","biking","skating","sports","playground","transportation","parking","roads","operator" and "open". These are the current, updated keywords. If this is okay for you, I will push it to the branch.

OK, I agree to use them. The "operator" keyword, though, seems redundant. The "roads" field might also be odd, don't you think so?

**Comment by AniSanikidze** [comment]
> > > > I'll try to change them.
> > > 
> > > 
> > > Actually, which single-word keyword do you suggest to use for "sports field"? As I need to modify the synonyms now
> > 
> > 
> > "wc","attractions","biking","skating","sports","playground","transportation","parking","roads","operator" and "open". These are the current, updated keywords. If this is okay for you, I will push it to the branch.
> 
> OK, I agree to use them. The "operator" keyword, though, seems redundant. The "roads" field might also be odd, don't you think so?

Yes, I think the operator is definitely redundant. I didn't even create a sentence for that, as I didn't understand the values properly. The "roads" field is acceptable to me. Should I remove the "operator" field?

**Comment by adzai** [comment]
Fixed in #33
