### ISSUE TITLE
Update fields in Bertramka data

### ISSUE THREAD

**Issue by irinakulinich3712** [adzai/chatbot#29]
It is necessary to add fields "dogs" and "skiing" to Bertramka park data, as these fields are present in data for other parks

**Comment by AniSanikidze** [comment]
But we don't have any information regarding "dogs" and" skiing" in Bertramka park. We can remove the dogs and skiing from the synonyms data structure for the ICA1 or we can write a separate function for identifying if the keyword does not exist in the chosen park's data. And output the message like this: There is no information provided about skiing in Bertramka park.

**Comment by irinakulinich3712** [comment]
> But we don't have any information regarding "dogs" and" skiing" in Bertramka park. We can remove the dogs and skiing from the synonyms data structure for the ICA1 or we can write a separate function for identifying if the keyword does not exist in the chosen park's data. And output the message like this: There is no information provided about skiing in Bertramka park.

"or we can write a separate function for identifying if the keyword does not exist in the chosen park's data" - this sounds good. Then, I can add this check of the keyword presence in the "find-park-data" function in the 028 branch. I will create an issue for that
