### ISSUE TITLE
Park can be chosen only once?

### ISSUE THREAD

**Issue by adzai** [adzai/chatbot#71]
From ICA1 feedback: "At the moment, choosing a park is irreversible."

As far as I can tell, changing the park can be done by using the `park` keyword,
in the  same way a username can be changed.
I also believe it is properly documented both in the README and in the `help` the
chatbot provides.
Can you confirm this?

**Comment by AniSanikidze** [comment]
Yes, you are 100% correct. Both README and help function mention changing park possibility and it's working perfectly. We can ask Petr for clarification.
